global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: pulse-ingestion
    static_configs:
      - targets: [ingestion:8080]
        labels:
          service: ingestion
    metrics_path: /metrics

  - job_name: pulse-query-api
    static_configs:
      - targets: [query-api:8080]
        labels:
          service: query-api
    metrics_path: /metrics

  - job_name: prometheus
    static_configs:
      - targets: [prometheus:9090]

  - job_name: pulse-workers
    static_configs:
      - targets: [persistence-worker:9091]
        labels:
          service: persistence-worker
      - targets: [analytics-worker:9091]
        labels:
          service: analytics-worker
      - targets: [webhook-worker:9091]
        labels:
          service: webhook-worker
    metrics_path: /metrics
