apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pulse.fullname" . }}-secret
  labels:
    {{- include "pulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  PULSE_ADMIN_TOKEN: {{ .Values.secrets.adminToken | quote }}
  PULSE_POSTGRES_DSN: {{ default .Values.config.postgresDSN .Values.secrets.postgresDSN | quote }}
  PULSE_REDIS_URL: {{ default .Values.config.redisURL .Values.secrets.redisURL | quote }}
